In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
folder_path = "C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data"

In [3]:
data = {}
for file in os.listdir(folder_path):
    # print(file.split(".")[0])
    data[file.split(".")[0].replace("olist_","").replace("_dataset","").replace("order_","")] = folder_path + "/" + file
data

{'customers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_customers_dataset.csv',
 'geolocation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_geolocation_dataset.csv',
 'orders': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_orders_dataset.csv',
 'items': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_items_dataset.csv',
 'payments': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_payments_dataset.csv',
 'reviews': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_reviews_dataset.csv',
 'products': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_products_dataset.csv',
 'sellers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_sellers_dataset.csv',
 'product_category_name_translation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/product_category_name_translation.csv'}

In [ ]:
#  7. How many orders are in the dataset?
#  df1["order_id"].nunique()
#  99,441 unique records.

In [17]:
df1 = pd.read_csv(data["orders"])

In [18]:
df1["order_id"].nunique()

99441

In [19]:
df1.order_id.count()

np.int64(99441)

In [20]:
len(df1)

99441

In [ ]:
# 8. How many customers?
# df2.customer_unique_id.nunique()
# 96,096-----------total number of unique customers

# customer_id = customer record associated with an order
# customer_unique_id = identifies the actual unique customer

In [22]:
df2 = pd.read_csv(data["customers"])

In [24]:
df2.nunique()

customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

In [25]:
df2.customer_unique_id.nunique()

96096

In [ ]:
# 9. How many sellers?
# 3,095 total number of sellers are there
# they can sell the products from their own country so too many countries involved in sellers dataset.

In [26]:
df3 = pd.read_csv(data["sellers"])

In [28]:
df3.nunique()

seller_id                 3095
seller_zip_code_prefix    2246
seller_city                611
seller_state                23
dtype: int64

In [119]:
df3["seller_id"]

0       3442f8959a84dea7ee197c632cb2df15
1       d1b65fc7debc3361ea86b5f14c68d2e2
2       ce3ad9de960102d0677a81f5d0bb7b2d
3       c0f3eea2e14555b6faeea3dd58c1b1c3
4       51a04a8a6bdcb23deccc82b0b80742cf
                      ...
3090    98dddbc4601dd4443ca174359b237166
3091    f8201cab383e484733266d1906e2fdfa
3092    74871d19219c7d518d0090283e03c137
3093    e603cf3fec55f8697c9059638d6c8eb5
3094    9e25199f6ef7e7c347120ff175652c3b
Name: seller_id, Length: 3095, dtype: object

In [ ]:
# 10. How many products?
# we have 32,951 diff types of products but categories are 73.
# if i use products table to find number of products i am getting 73 but if i use 
# product_category_name_english table then 71 coming. so 2 values are not translated to english

In [47]:
df4 = pd.read_csv(data["products"])

In [48]:
df4

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [36]:
df4.product_category_name.nunique()

73

In [58]:
df4.product_id.nunique()

32951

In [49]:
df5 = pd.read_csv(data["product_category_name_translation"])

In [50]:
df5

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [39]:
df5.product_category_name.nunique()

71

In [41]:
df5.product_category_name_english.nunique()

71

In [59]:
df = df4.merge(df5,on = "product_category_name",how = "left", indicator=True)

In [57]:
df = df4.merge(df5,on = "product_category_name",how = "left", indicator=True)


df.loc[
    df["_merge"] == "left_only",
    "product_category_name"
].unique()

array([nan, 'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'],
      dtype=object)

In [67]:
df.groupby("product_category_name_english")["product_id"].count()

product_category_name_english
agro_industry_and_commerce      74
air_conditioning               124
art                             55
arts_and_craftmanship           19
audio                           58
                              ...
stationery                     849
tablets_printing_image           9
telephony                     1134
toys                          1411
watches_gifts                 1329
Name: product_id, Length: 71, dtype: int64

In [46]:
df.nunique()

product_id                       32328
product_category_name               71
product_name_lenght                 66
product_description_lenght        2960
product_photos_qty                  19
product_weight_g                  2201
product_length_cm                   99
product_height_cm                  102
product_width_cm                    95
product_category_name_english       71
dtype: int64

In [111]:
# 11. How many order items?
# we have 1,12,650 records and 7 columns
df6 = pd.read_csv(data["items"])
df6.shape

(112650, 7)

In [117]:
df6.order_item_id.nunique()

21

In [113]:
df6.order_id.nunique()

98666

In [114]:
df6[["order_id","order_item_id"]].duplicated().sum()

np.int64(0)

In [115]:
df6[["order_id", "order_item_id"]].nunique()

order_id         98666
order_item_id       21
dtype: int64

In [116]:
df6.order_id.value_counts().head(20)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
c05d6a79e55da72ca780ce90364abed9    12
3a213fcdfe7d98be74ea0dc05a8b31ae    12
637617b3ffe9e2f7a2411243829226d0    12
af822dacd6f5cff7376413c03a388bb7    12
7f2c22c54cbae55091a09a9653fd2b8a    11
71dab1155600756af6de79de92e712e3    11
6c355e2913545fa6f72c40cbca57729e    11
5a3b1c29a49756e75f1ef513383c0c12    11
a483ffe0ce133740ab12ebcba8a3ccf9    10
9aec4e1ae90b23c7bf2d2b3bfafbd943    10
ca3625898fbd48669d50701aba51cd5f    10
Name: count, dtype: int64

In [82]:
df6.order_item_id.duplicated()

0         False
1          True
2          True
3          True
4          True
          ...
112645     True
112646     True
112647     True
112648     True
112649     True
Name: order_item_id, Length: 112650, dtype: bool

In [75]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [118]:
# 12. What is the date range of the orders?
#  '772 days 20:14:59'
#  I used order_purchase_timestamp because it represents when the order was purchased.
#  but this is in object datatype so i converted to datetime then i found min and max
# after that the range is max - min.

In [120]:
df7 = pd.read_csv(data["orders"])

In [171]:
df7.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [137]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [181]:
df7["order_purchase_timestamp"] = pd.to_datetime(df7["order_purchase_timestamp"])
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: datetime64[ns](1), object(7)
memory usage: 6.1+ MB

In [185]:
df7["order_purchase_timestamp"].dtype

dtype('<M8[ns]')

In [188]:
df7.describe()

            order_purchase_timestamp
count                          99441
mean   2017-12-31 08:43:12.776581120
min              2016-09-04 21:15:19
25%              2017-09-12 14:46:19
50%              2018-01-18 23:04:36
75%              2018-05-04 15:42:16
max              2018-10-17 17:30:18

In [196]:
min_date = df7["order_purchase_timestamp"].min()
max_date = df7["order_purchase_timestamp"].max()

In [202]:
time_range = max_date - min_date
time_range
years = time_range / pd.Timedelta(days=365.25)
years

2.115930837579537

In [203]:
time_range

Timedelta('772 days 20:14:59')

In [ ]:
# 13. Which columns contain dates?
# in reviews table ------>   review_creation_date , review_answer_timestamp ("but everything is in object datatype")
# in items table -------->   shipping_limit_date ("but everything is in object datatype")
# in orders table ------->   'order_purchase_timestamp','order_approved_at', 'order_delivered_carrier_date',
#                            'order_delivered_customer_date', 'order_estimated_delivery_date'("but everything is in object datatype")

# These columns were initially loaded as object datatype.
# They can be converted to datetime using pd.to_datetime() when needed.

In [204]:
data

{'customers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_customers_dataset.csv',
 'geolocation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_geolocation_dataset.csv',
 'orders': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_orders_dataset.csv',
 'items': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_items_dataset.csv',
 'payments': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_payments_dataset.csv',
 'reviews': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_reviews_dataset.csv',
 'products': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_products_dataset.csv',
 'sellers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_sellers_dataset.csv',
 'product_category_name_translation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/product_category_name_translation.csv'}

In [205]:
df1 = pd.read_csv(data["customers"])

In [235]:
df1.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [229]:
df2 = pd.read_csv(data["geolocation"])
df2

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [236]:
df3 = pd.read_csv(data["orders"])
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [238]:
df4 = pd.read_csv(data["items"])
df4.info()
# shipping_limit_date

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [218]:
df5 = pd.read_csv(data["payments"])
df5

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [237]:
df6 = pd.read_csv(data["reviews"])
df6.info()
# review_creation_date , review_answer_timestamp

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [225]:
df7 = pd.read_csv(data["products"])
df7

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [226]:
df8 = pd.read_csv(data["sellers"])
df8

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [227]:
df9 = pd.read_csv(data["product_category_name_translation"])
df9

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [239]:
# 14. Which columns contain missing values?
# in orders table we have 
order_approved_at               160,  0.160899 percent
order_delivered_carrier_date    1783,  1.793023 percent
order_delivered_customer_date    2965, 2.981668 percent

# in reviews table we have
review_comment_title       87656, 88.341530 percent
review_comment_message     58247, 58.702532 percent
# in products table we have
product_category_name         610, 1.851234  percent
product_name_lenght           610, 1.851234  percent
product_description_lenght    610, 1.851234  percent
product_photos_qty            610, 1.851234  percent
product_weight_g              2, 0.006070  percent
product_length_cm             2, 0.006070  percent
product_height_cm             2, 0.006070  percent
product_width_cm              2, 0.006070  percent

{'customers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_customers_dataset.csv',
 'geolocation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_geolocation_dataset.csv',
 'orders': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_orders_dataset.csv',
 'items': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_items_dataset.csv',
 'payments': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_payments_dataset.csv',
 'reviews': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_reviews_dataset.csv',
 'products': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_products_dataset.csv',
 'sellers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_sellers_dataset.csv',
 'product_category_name_translation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/product_category_name_translation.csv'}

In [250]:
df1 = pd.read_csv(data["customers"])
df1.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [252]:
df2 = pd.read_csv(data["geolocation"])
df2.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [271]:
df3 = pd.read_csv(data["orders"])
missing = df3.isnull().sum()
missing_percent = (missing/len(df3))*100
missing_percent

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [259]:
df4 = pd.read_csv(data["items"])
df4.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [260]:
df5 = pd.read_csv(data["payments"])
df5.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [272]:
df6 = pd.read_csv(data["reviews"])
missing = df6.isnull().sum()
missing_percent = (missing/len(df6))*100
missing_percent

review_id                   0.000000
order_id                    0.000000
review_score                0.000000
review_comment_title       88.341530
review_comment_message     58.702532
review_creation_date        0.000000
review_answer_timestamp     0.000000
dtype: float64

In [274]:
df7 = pd.read_csv(data["products"])
missing = df7.isnull().sum()
missing_percent = (missing/len(df7))*100
missing_percent

product_id                    0.000000
product_category_name         1.851234
product_name_lenght           1.851234
product_description_lenght    1.851234
product_photos_qty            1.851234
product_weight_g              0.006070
product_length_cm             0.006070
product_height_cm             0.006070
product_width_cm              0.006070
dtype: float64

In [263]:
df8 = pd.read_csv(data["sellers"])
df8.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [264]:
df9 = pd.read_csv(data["product_category_name_translation"])
df9.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [298]:
# 15. Which columns contain IDs?
# in customers table we have 'customer_id', 'customer_unique_id
# in orders table we have 'order_id', 'customer_id'
# in items table we have 'order_id', 'order_item_id', 'product_id', 'seller_id'
# in payments table we have 'order_id'
# in reviews table we have 'review_id', 'order_id'
# in products table we have 'product_id'
# in sellers table we have 'seller_id'

In [277]:
df1= pd.read_csv(data["customers"])
df1.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [280]:
df1= pd.read_csv(data["geolocation"])
df1.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [284]:
df1= pd.read_csv(data["orders"])
df1.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [286]:
df1= pd.read_csv(data["items"])
df1.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [288]:
df1= pd.read_csv(data["payments"])
df1.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [290]:
df1= pd.read_csv(data["reviews"])
df1.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [292]:
df1= pd.read_csv(data["products"])
df1.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [294]:
df1= pd.read_csv(data["sellers"])
df1.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [297]:
df1= pd.read_csv(data["product_category_name_translation"])
df1.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')