In [123]:

import pandas as pd
import os
import matplotlib.pyplot as plt
folder_path = "C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data"
data = {}
for file in os.listdir(folder_path):
    # print(file.split(".")[0])
    data[file.split(".")[0].replace("olist_","").replace("_dataset","").replace("order_","")] = folder_path + "/" + file

orders = pd.read_csv(data["orders"])
reviews = pd.read_csv(data["reviews"])
items = pd.read_csv(data["items"])

def clean_data(p_orders,p_reviews,p_items):
    
    order_date_cols = ['order_purchase_timestamp',
                       'order_approved_at', 
                       'order_delivered_carrier_date',
                       'order_delivered_customer_date', 
                       'order_estimated_delivery_date']
    for col in order_date_cols:
        p_orders[col] = pd.to_datetime(p_orders[col])
    
    review_date_cols = ['review_creation_date',
                        'review_answer_timestamp']
    for col in review_date_cols:
        p_reviews[col] = pd.to_datetime(p_reviews[col])
    
    item_date_cols = ['shipping_limit_date']
    for col in item_date_cols:
        p_items[col] = pd.to_datetime(p_items[col])
    return p_orders,p_reviews,p_items

orders,reviews,items = clean_data(orders,reviews,items)

In [124]:
import pandas as pd
import os
import matplotlib.pyplot as plt
folder_path = "C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data"
data = {}
for file in os.listdir(folder_path):
    # print(file.split(".")[0])
    data[file.split(".")[0].replace("olist_","").replace("_dataset","").replace("order_","")] = folder_path + "/" + file
data

{'customers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_customers_dataset.csv',
 'geolocation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_geolocation_dataset.csv',
 'orders': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_orders_dataset.csv',
 'items': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_items_dataset.csv',
 'payments': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_payments_dataset.csv',
 'reviews': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_reviews_dataset.csv',
 'products': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_products_dataset.csv',
 'sellers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_sellers_dataset.csv',
 'product_category_name_translation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/product_category_name_translation.csv'}

In [125]:
df9 = pd.read_csv(data["orders"])
df9.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [ ]:
# 27. What is the relationship between orders and customers?
cusomers , orders ------> customer_id
customers --------> customer_id----> PK
orders table -------> order_id -->PK , customer_id --->FK
most/all customer_ids have only one order, that is an observation about the customer records represented in the Orders table.
but if do groupby with customer_unique_id i got 2997 members created more than one order.

Orders and Customers are connected through customer_id. While most customer_id records are associated with one order, 
analysis using customer_unique_id shows that 2,997 unique customers placed more than one order, indicating repeat purchasing behavior.

In [126]:
df_customer = pd.read_csv(data["customers"])
df_customer.shape

(99441, 5)

In [127]:
df_orders = pd.read_csv(data["orders"])
df_orders.shape

(99441, 8)

In [6]:
orders_customers = pd.merge(df_customer,df_orders,on = "customer_id",how = "inner")

In [8]:
orders_customers.shape

(99441, 12)

In [15]:
orders_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00

In [46]:
df=(orders_customers.groupby("customer_unique_id")["order_id"].count().reset_index(name="order_count").sort_values("order_count",ascending=False))
df.head()

                     customer_unique_id  order_count
52973  8d50f5eadf50201ccdcedfb9e2ac8455           17
23472  3e43e6105506432c953e165fb2acf44c            9
37797  6469f99c1f9dfae7733b25662e7f1782            7
76082  ca77025e7201e3b30c44b472ff346268            7
10354  1b6c7548a2a1f9037c1fd3ddfed95f33            7

In [55]:
df[df["order_count"]>1].count()

customer_unique_id    2997
order_count           2997
dtype: int64

In [ ]:
# 28. What is the relationship between orders and payments?
orders ------> order_id --------> PK
payments------>order_id --------> FK
orders ---------> payments ----------> order_id("one to many relationship")
# how many orders have multiple payment records ----------->2961 records
# number of order payments by payment type
    payment_type
boleto         19784
credit_card    76795
debit_card      1529
not_defined        3
voucher         5775

Orders and Payments are connected through order_id. One order can have multiple payment records. 
In this dataset, 2,961 orders have multiple payment records. 
Credit card is the most frequently recorded payment type, followed by boleto, voucher, and debit card.

In [76]:
df_orders = pd.read_csv(data["orders"])
df_orders["order_id"].is_unique
df_orders.head()
df_orders.shape

(99441, 8)

In [113]:
df_payments = pd.read_csv(data["payments"])
df_payments["order_id"].is_unique
#df_payments.head()
#df_payments.shape

False

In [74]:
orders_payments = pd.merge(df_orders,df_payments,on="order_id",how="inner")
orders_payments.head()
orders_payments.shape

(103886, 12)

In [78]:
orders_payments.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,credit_card,1,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,3,voucher,1,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2,voucher,1,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,boleto,1,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,credit_card,3,179.12

In [100]:
# First, count how many payment records each order has:
df = orders_payments.groupby("order_id")["payment_sequential"].count().reset_index(name="payment_count").sort_values("payment_count",ascending=False)
#df[df["payment_count"]>1].shape
df

                               order_id  payment_count
97261  fa65dad1b0e818e3ccc5cb0e39231352             29
79611  ccf804e764ed5650cd8759557269dc13             26
15577  285c2e15bebd4ac83635ccc563dc71f4             22
53168  895ab968e7bb0d5659d16cd74cd1650c             21
99020  fedcd9f7ccdc8cba3a18defedd1a5547             19
...                                 ...            ...
33697  56bd45163229b35ca0ab490c1e3d3233              1
33696  56bc98e6d5b88c2cdb905f2fbec2ca3a              1
33695  56bbc7d92e6e74b8782abbf5ee336a92              1
33694  56bafc014f8ed2f34cfe598592c65fd8              1
99439  fffe41c64501cc87c801fd61db3f6244              1

[99440 rows x 2 columns]

In [93]:
df.head()

                               order_id  payment_count
97261  fa65dad1b0e818e3ccc5cb0e39231352             29
79611  ccf804e764ed5650cd8759557269dc13             26
15577  285c2e15bebd4ac83635ccc563dc71f4             22
53168  895ab968e7bb0d5659d16cd74cd1650c             21
99020  fedcd9f7ccdc8cba3a18defedd1a5547             19

In [114]:
# how many orders have multiple payment records
df[df["payment_count"]>1].count()

order_id         2961
payment_count    2961
dtype: int64

In [102]:
orders_payments.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,credit_card,1,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,3,voucher,1,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2,voucher,1,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,boleto,1,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,credit_card,3,179.12

In [109]:
df1 = orders_payments.groupby("payment_type")["order_id"].count()

In [107]:
df1

payment_type
boleto         19784
credit_card    76795
debit_card      1529
not_defined        3
voucher         5775
Name: order_id, dtype: int64

In [115]:
df2 = orders_payments.groupby("order_id")["payment_value"].sum().sort_values(ascending=False)
df2

order_id
03caa2c082116e1d31e67e9ae3700499    13664.08
736e1922ae60d0d6a89247b851902527     7274.88
0812eb902a67711a1cb742b3cdaa65ae     6929.31
fefacc66af859508bf1a7934eab1e97f     6922.21
f5136e38d1a14a4dbd87dff67da82701     6726.66
                                      ...
e8bbc1d69fee39eee4c72cb5c969e39d       10.07
f1d5c2e6867fa93ceee9ef9b34a53cbf        9.59
c8c528189310eaa44a745b8d9d26908b        0.00
00b1cb0320190ca0daa2c88b35206009        0.00
4637ca194b6387e2d538dc89b124b0ee        0.00
Name: payment_value, Length: 99440, dtype: float64

In [ ]:
# 29. What is the relationship between orders and order items?
orders ---------------> order_id----> PK
items -----> order_id,product_id,seller_id --------> FK
orders ------> items -----> order_id
orders ----> order_id ----> unique
items -----> order_id ----> not unique("one to many relationship")
how many orders have more than one item ------> 9803. so one order can have one or many order items. so relation is one to many(1:N)
maximum number of items in a single order ---> 21
combination of order_id and order_item_id in order_item table is unique

The orders and order_items tables have a one-to-many relationship through order_id. 
order_id is unique in the orders table but can appear multiple times in the order_items table because one order can contain multiple items. 
In this dataset, 9,803 orders have more than one item, and the maximum number of items in a single order is 21. 
The combination of order_id and order_item_id is unique in the order_items table.

In [156]:
df_orders = pd.read_csv(data["orders"])
df_orders["order_id"].is_unique

True

In [163]:
df_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

np.int64(0)

In [162]:
df_items = pd.read_csv(data["items"])
df_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [165]:
orders_items = pd.merge(df_orders,df_items,on="order_id",how="inner")
orders_items.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [158]:
df_items = pd.read_csv(data["items"])
df_items["order_item_id"].value_counts()
#df_items["order_id"].is_unique

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [138]:
df_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [160]:
df = df_items.groupby ("order_id")["order_item_id"].count().reset_index(name="counts").sort_values("counts",ascending=False)
#df[df["counts"]>1].count()
df

                               order_id  counts
50137  8272b63d03f5f79c56e9e4120aec44ef      21
10459  1b15974a0141d54e36626dca3fdc731a      20
65715  ab14fdcfbe524636d65ee38360e22ce8      20
60941  9ef13efd6949e4573a18964dd1bbe7f5      15
25583  428a2f660dc84138d969ccd69a0ab6d5      15
...                                 ...     ...
34640  5a0911d70c1f85d3bed0df1bf693a6dd       1
34639  5a082b558a3798d3e36d93bfa8ca1eae       1
34637  5a07264682e0b8fbb3f166edbbffc6e8       1
34636  5a071192a28951b76774e5a760c8c9b7       1
98665  fffe41c64501cc87c801fd61db3f6244       1

[98666 rows x 2 columns]

In [ ]:
30. What is the relationship between products and order items?
products ----> product_id ----> unique -----> PK
items ----> product_id -----> notunique ----> FK
products ----> items ----> product_id
one product can appear many times in order_item table
these number of times 14834 the product_id appear more than 1 time

How many products have been ordered at least once? 
df_items["product_id"].nunique() ----> 32951

How many products have been ordered more than once?
product_counts = df_items["product_id"].value_counts()
df = product_counts[product_counts>1].reset_index(name="count")
len(df) ------>14834

What is the maximum number of order items for a single product?
df.groupby("product_id")["order_id"].count().sort_values(ascending=False).max() ---->527

from products ---------------> items -----------> "one to many relationship"
from items ---------------> products -----------> "many to one relationship"

The relationship between Products and Order Items shows how frequently each catalog product is purchased. 
Products appearing frequently in order items indicate higher demand, 
which can support inventory planning, promotions, and product-level sales analysis.

In [190]:
df_products = pd.read_csv(data["products"])
#df_products.head(2)
df_products.shape

(32951, 9)

In [189]:
df_items = pd.read_csv(data["items"])
#df_items.head(2)
df_items.shape

(112650, 7)

In [208]:
df_items["product_id"].value_counts()

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
                                   ...
dbc42f8ad8afd0147a5a46be630781f8      1
5d86ed92606c80a89e547cdba3946812      1
0b8750fa58fefe42cf03a9e2e4b8fce6      1
a4758e74e2cdb74d0c4db83594ca14a3      1
350688d9dc1e75ff97be326363655e01      1
Name: count, Length: 32951, dtype: int64

In [187]:
df1 = df.sort_values("order_count",ascending=False)
df1

                             product_id  order_count
22112  aca2eb7d00ea1a7b8ebd4e68314663af          527
19742  99a4788cb24856965c36a24e339b6058          488
8613   422879e10f46682990de24d770e7f83d          484
7364   389d119b48cf3043d311335e499d9c6b          392
7079   368c6c730842d78016ad823897a372db          388
...                                 ...          ...
14037  6ca99f05e9c1952a6597264e87f01378            1
14036  6ca54e191592a843087a042b0665d7ef            1
14035  6ca5428af5edb5066b1966ad58501b60            1
14034  6ca32b4631431cb1fe976880797a0f5c            1
32950  fffe9eeff12fcbd74a2f2b007dde0c58            1

[32951 rows x 2 columns]

In [214]:
df_products["product_id"].is_unique
df_items["product_id"].is_unique
df = df_items.groupby("product_id")["order_id"].count().reset_index(name="order_count")
df1 = df.sort_values("order_count",ascending=False)
df1[df1["order_count"]>1].count()

product_id     14834
order_count    14834
dtype: int64

In [221]:
df = pd.merge(df_products,df_items,on = "product_id",how = "inner")
df.shape

(112650, 15)

In [201]:
df_items.head(2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

In [205]:
df_items["product_id"].nunique()

32951

In [219]:
product_counts = df_items["product_id"].value_counts()
df = product_counts[product_counts>1].reset_index(name="count")
len(df)

14834

In [213]:
counts = df_items["product_id"].value_counts()

df_items[df_items["product_id"].isin(counts[counts > 1].index)]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69
...,...,...,...,...,...,...,...
112644,fffbee3b5462987e66fb49b1c5411df2,1,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72

In [220]:
df = product_counts[product_counts>1].reset_index(name="count")
df.shape

(14834, 2)

In [238]:
What is the maximum number of order items for a single product?
df.groupby("product_id")["order_id"].count().sort_values(ascending=False).max()

Object `product` not found.

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
                                   ...
6ca99f05e9c1952a6597264e87f01378      1
6ca54e191592a843087a042b0665d7ef      1
6ca5428af5edb5066b1966ad58501b60      1
6ca32b4631431cb1fe976880797a0f5c      1
fffe9eeff12fcbd74a2f2b007dde0c58      1
Name: order_id, Length: 32951, dtype: int64

In [223]:
df.head(2)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,order_id,order_item_id,seller_id,shipping_limit_date,price,freight_value
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,e17e4f88e31525f7deef66779844ddce,1,5670f4db5b62c43d542e1b2d56b0cf7c,2018-04-30 17:33:54,10.91,7.39
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,5236307716393b7114b53ee991f36956,1,b561927807645834b59ef0d16ba55a24,2018-02-06 19:11:15,248.00,17.99

In [237]:
product_counts[product_counts == product_counts.max()]

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
Name: count, dtype: int64

In [236]:
df.groupby("product_id")["order_id"].count().sort_values(ascending=False).max()

527

In [242]:
product_counts[product_counts == product_counts.max()]

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
Name: count, dtype: int64

In [ ]:
Is the relationship between products and order_items one-to-many or many-to-one?

In [244]:
df_products.head(2)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

In [245]:
df_items.head(2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

In [250]:
df_products["product_id"].is_unique
df_items["product_id"].duplicated().sum()
df_items["product_id"].value_counts()

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
                                   ...
dbc42f8ad8afd0147a5a46be630781f8      1
5d86ed92606c80a89e547cdba3946812      1
0b8750fa58fefe42cf03a9e2e4b8fce6      1
a4758e74e2cdb74d0c4db83594ca14a3      1
350688d9dc1e75ff97be326363655e01      1
Name: count, Length: 32951, dtype: int64

In [ ]:
31. What is the relationship between sellers and order items?
sellers ----> seller_id ----> unique -----> PK
items ------> seller_id -----> notunique -----> FK
sellers ---------> items -----------> seller_id
from sellers ---------> items ----------> "one to many relationship"
from items ---------> sellers ----------> "many to one relationship"
this seller_id has the maximun number of order-item records,6560211a19b47992c3666cc44a7e94c0,order_count with 2033 records
2586 seller_id s got more than 1 order item
509 seller_id s got only one order item
this product_id appears in the highest number of order-item records aca2eb7d00ea1a7b8ebd4e68314663af with 527 records
14834 this number of product_id s have morethan 1 order
every seller id has atleast 1 order id
seller_counts = df_items["seller_id"].value_counts()
seller_counts.index
no_order_sellers = df_sellers[~df_sellers["seller_id"].isin(seller_counts.index)]

Some sellers have many orders, while others have only a few. 
This helps us understand which sellers are more active and how sales are distributed among sellers.

In [310]:
df_sellers = pd.read_csv(data["sellers"])
df_sellers.head(2)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

In [254]:
df_items = pd.read_csv(data["items"])
df_items.head(2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

In [325]:
seller_counts = df_items["seller_id"].value_counts()
(seller_counts>1).sum() / len(df_sellers) * 100

np.float64(83.5541195476575)

In [323]:
no_order_sellers = df_sellers[~df_sellers["seller_id"].isin(seller_counts.index)]
no_order_sellers

Empty DataFrame
Columns: [seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [318]:
df_sellers["seller_id"]

0       3442f8959a84dea7ee197c632cb2df15
1       d1b65fc7debc3361ea86b5f14c68d2e2
2       ce3ad9de960102d0677a81f5d0bb7b2d
3       c0f3eea2e14555b6faeea3dd58c1b1c3
4       51a04a8a6bdcb23deccc82b0b80742cf
                      ...
3090    98dddbc4601dd4443ca174359b237166
3091    f8201cab383e484733266d1906e2fdfa
3092    74871d19219c7d518d0090283e03c137
3093    e603cf3fec55f8697c9059638d6c8eb5
3094    9e25199f6ef7e7c347120ff175652c3b
Name: seller_id, Length: 3095, dtype: object

In [315]:
percentage = (
    len(no_order_sellers) / len(df_sellers)
) * 100

percentage

0.0

In [317]:
percentage = (
    ~df_sellers["seller_id"].isin(df_items["seller_id"])
).mean() * 100
percentage

np.float64(0.0)

In [302]:
df_sellers["seller_id"].is_unique
df_items["seller_id"].is_unique
df_items["product_id"].is_unique

False

In [301]:
df = df_items.groupby("seller_id")["order_id"].count().sort_values(ascending=False)
df

seller_id
6560211a19b47992c3666cc44a7e94c0    2033
4a3ca9315b744ce9f8e9374361493884    1987
1f50f920176fa81dab994f9023523100    1931
cc419e0650a3c5ba77189a1882b7556a    1775
da8622b14eb17ae2831f4ac5b9dab84a    1551
                                    ...
5f57db27027655e6c6a391601daa0258       1
5e25c632f9db6cfb8bc100421c2737b6       1
5e106d93b717c2682b9383da480364a1       1
d36b07fd3c5088e477a72d1fccfe29d4       1
7d81e74a4755b552267cd5e081563028       1
Name: order_id, Length: 3095, dtype: int64

In [278]:
df1 = df.sort_values(ascending=False).reset_index(name="order_count")

In [294]:
df1[df1["order_count"]==1].nunique()

seller_id      509
order_count      1
dtype: int64

In [286]:
(df1["order_count"]>1).sum()

np.int64(2586)

In [297]:
df1.loc[df1["order_count"] > 1, "order_count"].sum()

np.int64(112141)

In [308]:
df = df_items.groupby("product_id")["order_id"].count().reset_index(name="order_count").sort_values("order_count",ascending=False)
df[df["order_count"] >1].sum()

product_id     aca2eb7d00ea1a7b8ebd4e68314663af99a4788cb24856...
order_count                                                94533
dtype: object

In [309]:
(df["order_count"] > 1).sum()

np.int64(14834)

In [ ]:
32. Which table should be the starting point for revenue analysis?
I would start revenue analysis with the Order Items table because it contains the product-level price information. 
I can then join it with Orders, Products, Customers, Sellers, and Payments depending on the business question.

In [ ]:
Overall conclusion for Q27–Q32

Overall, the Olist dataset has a relational structure centered around orders, 
with order_id, customer_id, product_id, and seller_id connecting the major tables. 
Orders can contain multiple payment records and multiple order items, 
creating one-to-many relationships with the Payments and Order Items tables.

The customer analysis shows that while a customer_id is generally associated with one order record, 
using customer_unique_id reveals repeat purchasing behavior, with 2,997 unique customers placing more than one order. 
This distinction is important because customer_id and customer_unique_id represent different levels of customer identity.

Order Items provides the detailed product-level transaction information. 
It connects orders with products and sellers, allowing us to analyze product demand and seller activity. 
The Products → Order Items and Sellers → Order Items relationships are one-to-many 
because a single product or seller can appear in many order-item records.

The product analysis shows that 32,951 products were ordered at least once, 
while 14,834 products appeared in more than one order-item record. 
The most frequently appearing product had 527 order-item records. 
Similarly, seller activity varies considerably: some sellers have many order-item records while others have only a small number.

For revenue analysis, the Order Items table is an appropriate starting point 
because it contains product-level price and freight_value information. 
It can then be joined with Orders, Products, Customers, Sellers, and Payments depending on the business question.

Overall, these relationships provide the foundation for analyzing customer behavior, repeat purchases, product demand, seller performance, payment behavior, and revenue.